### ISSUE TITLE
Go mod path mismatch, can't install

### ISSUE THREAD

**Issue by dmorawetz** [dennis-tra/shamir#1]
Thanks for this great, simple CLI!

Please change the path in your `go.mod` file to `github.com/dennis-tra/shamir` so go install can install it correctly.

Currently I get the following error message:
```
go: downloading github.com/dennis-tra/shamir v0.0.0-20220516193728-1e81352389e1
go: github.com/dennis-tra/shamir@latest: github.com/dennis-tra/shamir@v0.0.0-20220516193728-1e81352389e1: parsing go.mod:
        module declares its path as: shamir
                but was required as: github.com/dennis-tra/shamir
```

And maybe consider adding a [version tag](https://go.dev/ref/mod#versions) like `v0.1.0` for easier tracking of changes.

**Comment by dennis-tra** [comment]
Oh damn, thanks for reporting @dmorawetz ! I've put it on my list and will update as soon as time permits :)

**Comment by dennis-tra** [comment]
Done :) thanks, again!
